Story/validate diarrhoea 52
breathoscope/breathoscope pull request #10
Opened 2019-03-01 09:54 UTC by AndriiKhlivniuk

Validating diarrhoea by asking questions. User can answer yes or no.

2019-03-09 19:28 UTC, blottn commented
This is missing some files and can't compile yet. Make sure to include the `activity_validate_diarrhoea` layout.

2019-03-09 20:03 UTC, WhelanB commented on app/src/main/java/org/inspire/breath/validateDiarrhoea.java
> +            public void onClick(View v) {
Can this be reduced to just the inner 3 lines using the index? The if/else checks are redundant

2019-03-09 20:22 UTC, AndriiKhlivniuk commented
Yes. I have changed this and pushed again. Can you review it, please?

On Sat, 9 Mar 2019 at 20:03, Brian Whelan <notifications@github.com> wrote:

> *@WhelanB* commented on this pull request.
> ------------------------------
>
> In app/src/main/java/org/inspire/breath/validateDiarrhoea.java
> <https://github.com/breathoscope/breathoscope/pull/10#discussion_r264012623>
> :
>
> > +                    questionNum++;
> +                    question.setText(mQuestions.getQuestion(questionNum));
> +                }
> +                else if (questionNum>=2){
> +                    question.setText(mQuestions.getAnswer(1));
> +                    answerYes.setVisibility(View.GONE);
> +                    answerNo.setVisibility(View.GONE);
> +                }
> +
> +
> +            }
> +        });
> +
> +        answerNo.setOnClickListener(new View.OnClickListener() {
> +            @Override
> +            public void onClick(View v) {
>
> Can this be reduced to just the inner 3 lines using the index? The if/else
> checks are redundant
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/breathoscope/breathoscope/pull/10#pullrequestreview-212575332>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYWKWjd9jNQBTyhm-yg7cz8yqWImlGPCks5vVBOagaJpZM4bYp4s>
> .
>

2019-03-11 20:33 UTC, WhelanB requested changes

2019-03-11 20:33 UTC, WhelanB commented on app/src/main/java/org/inspire/breath/validateDiarrhoea.java
> +public class validateDiarrhoea extends AppCompatActivity {
could you move this class into org.inspire.breath.activities (see master branch)?

2019-03-11 21:39 UTC, AndriiKhlivniuk commented
Moved class as asked

пн, 11 марта 2019 г. в 20:33, Brian Whelan <notifications@github.com>:

> *@WhelanB* requested changes on this pull request.
> ------------------------------
>
> In app/src/main/java/org/inspire/breath/validateDiarrhoea.java
> <https://github.com/breathoscope/breathoscope/pull/10#discussion_r264407137>
> :
>
> > @@ -0,0 +1,59 @@
> +package org.inspire.breath;
> +
> +import android.support.v7.app.AppCompatActivity;
> +import android.os.Bundle;
> +import android.view.View;
> +import android.widget.TextView;
> +import android.widget.Button;
> +
> +public class validateDiarrhoea extends AppCompatActivity {
>
> could you move this class into org.inspire.breath.activities (see master
> branch)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/breathoscope/breathoscope/pull/10#pullrequestreview-213056894>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYWKWv64x6GldyQReWADPI4llYwgirr6ks5vVr2SgaJpZM4bYp4s>
> .
>

2019-03-13 16:25 UTC, blottn commented
Closing Duplicate

2019-03-13 16:25 UTC, closed without merging