Questions to validate diarrhoea
breathoscope/breathoscope pull request #19
Opened 2019-03-13 13:59 UTC by AndriiKhlivniuk

2019-03-14 10:32 UTC, blottn submitted a review, later dismissed
Some things need to be changed, most notably the answers aren't being stored anywhere yet.

2019-03-14 10:32 UTC, blottn commented on app/src/main/java/org/inspire/breath/activities/Questions.java
> +        return question;
These are just wrappers around the array access operatorx

2019-03-14 10:32 UTC, blottn commented on app/src/main/java/org/inspire/breath/activities/Questions.java
> +package org.inspire.breath.activities;
Since this is just a data class it should be in the data packages.

2019-03-14 10:32 UTC, blottn commented on app/src/main/java/org/inspire/breath/activities/Questions.java
> +    public String mAnswers [] = {
Since this class will only be used once to describe the questions it makes more sense for these arrays to be member values of the Activity

2019-03-22 10:19 UTC, WhelanB requested changes

2019-03-22 10:19 UTC, WhelanB commented on app/src/main/java/org/inspire/breath/activities/ValidateDiarrhoeaActivity.java
> +                if (questionNum<2) {
Instead of 2 could you base this number off the array length?

2019-03-22 10:19 UTC, WhelanB commented on app/src/main/java/org/inspire/breath/activities/ValidateDiarrhoeaActivity.java
> +                else if (questionNum>=2){
ditto here

2019-03-22 10:19 UTC, WhelanB commented on app/src/main/java/org/inspire/breath/activities/ValidateDiarrhoeaActivity.java
> +package org.inspire.breath.activities;
The final result of these questions needs to be stored into the DB under the patient profile (see DiarrhoeaTestResult.java)

2019-04-04 15:22 UTC, WhelanB approved these changes

2019-04-04 15:25 UTC, merged