Story/malaria rec 50
breathoscope/breathoscope pull request #5
Opened 2019-02-12 17:41 UTC by WhelanB

Adds a new activity to handle Malaria RDT content
Adds a fragment to handle photography of the Malaria RDT

2019-02-13 10:47 UTC, blottn requested changes
Malaria activity shouldn't be the main activity so probably can comment out/ remove line 14 of the manifest

2019-02-26 11:27 UTC, moloney1 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".activities.MalariaActivity">
```suggestion
        <activity android:name=".LoginActivity">
```

2019-02-26 11:28 UTC, moloney1 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".LoginActivity"></activity>
```suggestion
        <activity android:name=".activities.MalariaActivity"></activity>
```

2019-02-26 11:29 UTC, blottn approved these changes

2019-02-26 11:29 UTC, merged